name: deploy-with secrets 
on: workflow_dispatch
env:
    MONGODB_DB_NAME: "gh-actions-db"
jobs:
  test:
    env:
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_CLUSTER_ADDRESS: cluster0.sh3q3.mongodb.net/
      PORT: 8080
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
      - name: Run server
        run: npm start & npx wait-on http://127.0.0.1:$PORT
      - name: Run tests
        run: npm test
      - name: Output information # this will not print the username and password as they are now secrets
        run: echo "MONGODB_USERNAME:$MONGODB_USERNAME" # or MONGODB_USERNAME:${{ env.MONGODB_USERNAME }}
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information # this will not print the username and password as they are now secrets
        run: |        
          echo "MONGODB_DB_NAME:$MONGODB_DB_NAME"
